// <auto-generated />
using System;
using FlowerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowerApp.Data.Migrations
{
    [DbContext(typeof(FlowerAppContext))]
    [Migration("20241027170524_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowerApp.Domain.DbModels.Flower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppearanceDescription")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("CareDescription")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<int>("LightParametersId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<short>("ToxicCategory")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TransplantFrequency")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WateringFrequency")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LightParametersId");

                    b.ToTable("Flowers");
                });

            modelBuilder.Entity("FlowerApp.Domain.DbModels.LightParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInHours")
                        .HasColumnType("integer");

                    b.Property<double>("IlluminationInSuites")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("LightParameters");

                    b.HasCheckConstraint("CK_DurationInHours", "\"DurationInHours\" >= 0");

                    b.HasCheckConstraint("CK_IlluminationInSuites", "\"IlluminationInSuites\" >= 0");
                });

            modelBuilder.Entity("FlowerApp.Domain.DbModels.Flower", b =>
                {
                    b.HasOne("FlowerApp.Domain.DbModels.LightParameters", "LightParameters")
                        .WithMany("Flowers")
                        .HasForeignKey("LightParametersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LightParameters");
                });

            modelBuilder.Entity("FlowerApp.Domain.DbModels.LightParameters", b =>
                {
                    b.Navigation("Flowers");
                });
#pragma warning restore 612, 618
        }
    }
}
